// Code in this package is generated by bpf2go. abi_test.go is hand-written and
// asserts map shapes for the DNS sniff BPF object.
//
// Pure spec parse via cilium/ebpf — no kernel needed.
package tracedns

import (
	"testing"

	"github.com/cilium/ebpf"
)

func TestDNSMapShapes(t *testing.T) {
	spec, err := LoadTracedns()
	if err != nil {
		t.Fatalf("LoadTracedns: %v", err)
	}

	t.Run("dns_events is ringbuf with 1<<24 max_entries", func(t *testing.T) {
		ms, ok := spec.Maps["dns_events"]
		if !ok {
			t.Fatal("map dns_events not found in CollectionSpec")
		}
		if ms.Type != ebpf.RingBuf {
			t.Errorf("dns_events type = %v, want ebpf.RingBuf", ms.Type)
		}
		if ms.MaxEntries != 1<<24 {
			t.Errorf("dns_events MaxEntries = %d, want %d (1<<24)", ms.MaxEntries, 1<<24)
		}
	})

	t.Run("dns_ringbuf_reserve_failures is PERCPU_ARRAY", func(t *testing.T) {
		ms, ok := spec.Maps["dns_ringbuf_reserve_failures"]
		if !ok {
			t.Fatal(`map "dns_ringbuf_reserve_failures" not found`)
		}
		if ms.Type != ebpf.PerCPUArray {
			t.Fatalf("type = %v, want ebpf.PerCPUArray", ms.Type)
		}
		if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
			t.Fatalf("unexpected shape %+v", ms)
		}
	})
}
