// Code in this package is generated by bpf2go. abi_test.go is hand-written
// and asserts key map-shape contracts for the trace_connect BPF object.
//
// Pure spec parse via cilium/ebpf — no kernel needed.
package traceconnect

import (
	"testing"

	"github.com/cilium/ebpf"
)

func TestTraceconnectMapShapes(t *testing.T) {
	spec, err := LoadTraceconnect()
	if err != nil {
		t.Fatalf("LoadTraceconnect: %v", err)
	}

	t.Run("ringbuf maps keep 1<<24 capacity", func(t *testing.T) {
		ringbufMaps := []string{"connect_events", "udp_events", "http_events", "tls_events"}
		for _, name := range ringbufMaps {
			ms, ok := spec.Maps[name]
			if !ok {
				t.Fatalf("map %s not found in CollectionSpec", name)
			}
			if ms.Type != ebpf.RingBuf {
				t.Errorf("%s type = %v, want ebpf.RingBuf", name, ms.Type)
			}
			if ms.MaxEntries != 1<<24 {
				t.Errorf("%s MaxEntries = %d, want %d (1<<24)", name, ms.MaxEntries, 1<<24)
			}
		}
	})

	t.Run("connect4_by_tgid_fd stays bounded LRU hash", func(t *testing.T) {
		ms, ok := spec.Maps["connect4_by_tgid_fd"]
		if !ok {
			t.Fatal("map connect4_by_tgid_fd not found in CollectionSpec")
		}
		if ms.Type != ebpf.LRUHash {
			t.Errorf("connect4_by_tgid_fd type = %v, want ebpf.LRUHash", ms.Type)
		}
		if ms.MaxEntries != 16384 {
			t.Errorf("connect4_by_tgid_fd MaxEntries = %d, want 16384", ms.MaxEntries)
		}
		if ms.KeySize != 8 {
			t.Errorf("connect4_by_tgid_fd KeySize = %d, want 8", ms.KeySize)
		}
		if ms.ValueSize != 8 {
			t.Errorf("connect4_by_tgid_fd ValueSize = %d, want 8", ms.ValueSize)
		}
	})

	t.Run("singleton ARRAY control and observation maps", func(t *testing.T) {
		cases := []struct {
			mapName   string
			valueSize uint32
		}{
			{"tls_agent_cfg", 1},
			{"udp_sendmsg_multi_iovec_observed", 4},
			{"tls_writev_multi_iovec_observed", 4},
			{"unobserved_egress_syscalls_observed", 4},
			{"io_uring_setup_observed", 4},
			{"canary_trigger", 8},
		}
		for _, c := range cases {
			ms, ok := spec.Maps[c.mapName]
			if !ok {
				t.Errorf("map %s not found in CollectionSpec", c.mapName)
				continue
			}
			if ms.Type != ebpf.Array {
				t.Errorf("%s type = %v, want ebpf.Array", c.mapName, ms.Type)
			}
			if ms.MaxEntries != 1 {
				t.Errorf("%s MaxEntries = %d, want 1", c.mapName, ms.MaxEntries)
			}
			if ms.KeySize != 4 {
				t.Errorf("%s KeySize = %d, want 4", c.mapName, ms.KeySize)
			}
			if ms.ValueSize != c.valueSize {
				t.Errorf("%s ValueSize = %d, want %d", c.mapName, ms.ValueSize, c.valueSize)
			}
		}
	})

	t.Run("PERCPU_ARRAY reserve and tuple failure maps", func(t *testing.T) {
		names := []string{
			"connect4_tuple_update_failures",
			"udp_ringbuf_reserve_failures",
			"connect_ringbuf_reserve_failures",
			"http_ringbuf_reserve_failures",
			"tls_ringbuf_reserve_failures",
		}
		for _, name := range names {
			ms, ok := spec.Maps[name]
			if !ok {
				t.Errorf("map %s not found in CollectionSpec", name)
				continue
			}
			if ms.Type != ebpf.PerCPUArray {
				t.Errorf("%s type = %v, want ebpf.PerCPUArray", name, ms.Type)
			}
			if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
				t.Errorf("%s unexpected shape MaxEntries=%d KeySize=%d ValueSize=%d",
					name, ms.MaxEntries, ms.KeySize, ms.ValueSize)
			}
		}
	})
}
