// Code in this package is generated by bpf2go. abi_test.go is hand-written
// and asserts the BPF map shape contract: map types and MaxEntries for the
// bpf_audit BPF object.
//
// bpf_audit_events is intentionally small (4 KiB / 1<<12) because bpf(2)
// volume on a GitHub-hosted runner is low. If the ring fills, the reserve-
// failure counter increments and userspace surfaces it in readiness JSON.
//
// Pure spec parse via cilium/ebpf — no kernel needed.

package tracebpfaudit

import (
	"testing"

	"github.com/cilium/ebpf"
)

func TestBPFAuditMapShapes(t *testing.T) {
	spec, err := LoadTracebpfaudit()
	if err != nil {
		t.Fatalf("LoadTracebpfaudit: %v", err)
	}

	t.Run("bpf_audit_events is ringbuf with 4096 max_entries", func(t *testing.T) {
		ms, ok := spec.Maps["bpf_audit_events"]
		if !ok {
			t.Fatal("map bpf_audit_events not found in CollectionSpec")
		}
		if ms.Type != ebpf.RingBuf {
			t.Errorf("bpf_audit_events type = %v, want ebpf.RingBuf", ms.Type)
		}
		if ms.MaxEntries != 4096 {
			t.Errorf("bpf_audit_events MaxEntries = %d, want 4096 (1<<12)", ms.MaxEntries)
		}
	})

	t.Run("bpf_audit_reserve_failures is array with 1 entry", func(t *testing.T) {
		ms, ok := spec.Maps["bpf_audit_reserve_failures"]
		if !ok {
			t.Fatal("map bpf_audit_reserve_failures not found in CollectionSpec")
		}
		if ms.Type != ebpf.Array {
			t.Errorf("bpf_audit_reserve_failures type = %v, want ebpf.Array", ms.Type)
		}
		if ms.MaxEntries != 1 {
			t.Errorf("bpf_audit_reserve_failures MaxEntries = %d, want 1", ms.MaxEntries)
		}
	})
}
