// Code in this package is generated by bpf2go. abi_test.go is hand-written
// and asserts the BPF↔Go capacity contract: the embedded ELF's
// `MaxEntries` for each LSM enforce map must match the Go-side `policy.*`
// constants that callers use to gate inserts. Drift here equals silent
// BPF EINVAL on Update, surfacing as enforce-bypass in production.
//
// Mirrors the contract established in internal/bpf/traceenforce/abi_test.go.
//
// Pure spec parse via cilium/ebpf — no kernel needed; runs on any OS/arch
// covered by the generated _bpfel.go build constraints.

package tracelsmenforce

import (
	"testing"

	"github.com/cilium/ebpf"
	"github.com/coldstep-io/coldstep/internal/policy"
)

func TestLSMEnforceMapMaxEntriesMatchGoConstants(t *testing.T) {
	spec, err := LoadTracelsmenforce()
	if err != nil {
		t.Fatalf("LoadTracelsmenforce: %v", err)
	}

	cases := []struct {
		mapName        string
		expected       uint32
		goConstantName string
	}{
		{"lsm_allowed_ipv4", uint32(policy.MaxAllowedEnforceIPv4Keys), "policy.MaxAllowedEnforceIPv4Keys"},
		{"lsm_ignored_ipv4_lpm", uint32(policy.MaxIgnoredIPv4Nets), "policy.MaxIgnoredIPv4Nets"},
	}

	for _, c := range cases {
		ms, ok := spec.Maps[c.mapName]
		if !ok {
			t.Errorf("BPF map %q not found in CollectionSpec", c.mapName)
			continue
		}
		if ms.MaxEntries != c.expected {
			t.Errorf("BPF map %q MaxEntries = %d, want %d (Go constant %s)",
				c.mapName, ms.MaxEntries, c.expected, c.goConstantName)
		}
	}
}

func TestLSMDenyReserveFailuresMapIsPerCPUArray(t *testing.T) {
	spec, err := LoadTracelsmenforce()
	if err != nil {
		t.Fatalf("LoadTracelsmenforce: %v", err)
	}
	ms, ok := spec.Maps["lsm_deny_reserve_failures"]
	if !ok {
		t.Fatal(`BPF map "lsm_deny_reserve_failures" missing`)
	}
	if ms.Type != ebpf.PerCPUArray {
		t.Fatalf("lsm_deny_reserve_failures type = %v, want ebpf.PerCPUArray", ms.Type)
	}
	if ms.MaxEntries != 1 || ms.KeySize != 4 || ms.ValueSize != 4 {
		t.Fatalf("unexpected shape MaxEntries=%d KeySize=%d ValueSize=%d",
			ms.MaxEntries, ms.KeySize, ms.ValueSize)
	}
}
